<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('ZF2 Doctrine Skeleton'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath('assets/style.css?' . filemtime('public/assets/style.css')), array('media' => 'all'))
            ->prependStylesheet($this->basePath('assets/bootstrap-3.3.7/css/bootstrap-theme.min.css'), array('media' => 'all'))
            ->prependStylesheet($this->basePath('assets/bootstrap-3.3.7/css/bootstrap.min.css'), array('media' => 'all')) ?>
        <?php echo $this->headStyle(); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('assets/bootstrap-3.3.7/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/jquery-3.1.1/jquery.min.js'))
            ->prependFile($this->basePath('assets/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('assets/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">VIS</a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php // <-- Update this !!
                    echo $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(1)
                        ->setRenderInvisible(false)
                        ->setOnlyActiveBranch(false)
                        ->setUlClass('nav navbar-nav');
                    ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php
            echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
            echo $this->flashMessenger()->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
            echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
            echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
            echo $this->content;
            ?>
        </div>
        <footer class="footer">
            <div class="container">
                <p class="text-right">&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
